### ISSUE TITLE
Medusa: Production ready testnet on Filecoin & Arbitrum, Public launch

### ISSUE THREAD

**Issue by maxscience** [cryptonetlab/roadmap#34]
eta: 2023-03-30
Objectives:
- FVM support at Spacewarp (done)
- Public launch with new website (expected on Feb 10)

**Comment by momack2** [comment]
can you add "Medusa" to the title (and for all other medusa roadmap items)?

**Comment by maxscience** [comment]
> can you add "Medusa" to the title (and for all other medusa roadmap items)?

Done
